version: '3.3'

volumes:
  pqldb:
   driver: local

services:
  db:
    image: postgres:10.6
    command: "-p 3306 -N 500"
    restart: always
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: root
    expose:
        - "33060"
    ports:
        - "33060:3306"
    volumes:
        - pqldb:/var/lib/postgresql/data
    network_mode: bridge

  distro:
    build:
      context: . 
      dockerfile: /home/test/Dockerfile

  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_port=80
    links:
      - db:database
      - distro
